name: Rendezvous Interoperability Tests (PR)

on:
  pull_request:
    paths:
      - 'rendezvous/**'
      - '.github/actions/run-bash-rendezvous-test/**'
      - '.github/workflows/rendezvous-interop-pr.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-tests:
    runs-on: [self-hosted, linux, x64, ephemeral]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run rendezvous interop tests
        uses: ./.github/actions/run-bash-rendezvous-test
